version: "3.9"
services:
  # # Install Source Oracle DB and setup the Customer database
  oracle-1:
    container_name: src-database
    image: gvenzl/oracle-xe:11
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: root
      APP_USER: myuser
      APP_USER_PASSWORD: mypassword
    volumes:
      - ./startup.sql:/container-entrypoint-startdb.d/1-startup.sql

  # # Install Source Oracle DB and setup the Customer database
  oracle-2:
    container_name: tgt-database
    image: gvenzl/oracle-xe:11
    ports:
      - 1522:1521
    environment:
      ORACLE_PASSWORD: root
      APP_USER: myuser
      APP_USER_PASSWORD: mypassword

  debezium:
    container_name: src-orcl-dbz
    build: .
    # image: quay.io/debezium/server:2.3.4.Final
    depends_on: 
      - oracle-1
    volumes:
      - ./debezium-orcl.properties:/debezium/conf/application.properties
      #- ./data:/debezium/data
